# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Yuchen Chen
description: >- # this means to ignore newlines until "baseurl:"
  Finance Ph.D Candidate, University of Minnesota.
baseurl: "/homepage" # the subpath of the site
url: "https://chen3912.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-21506388-8"

header:
  pages:
    - name: Home       
      slug: /          # <-- index.md
    - name: Research  
    - name: Teaching

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: chen3912@umn.edu
      link: mailto:chen3912@umn.edu

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
